<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
?>
<div
    class="livechat-wrapper"
    x-data="initLiveChat()"
    x-bind="eventListeners"
    :class="{ 'w-auto! h-auto!': !open }"
    @keyup.escape="open = false"
    @click.outside="open = false"
>
    <?= /** @noEscape */ $block->getChildHtml('button') ?>

    <div
        x-show="open"
        x-cloak
        class="livechat"
        :class='{ ["layout-" + layout]: true }'
        x-transition
        role="dialog"
        aria-labelledby="livechat-title"
    >
        <?= /** @noEscape */ $block->getChildHtml('layout') ?>
    </div>
</div>
